apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VultrBareMetalMachineTemplate
metadata:
  name: vultr-bare-metal-control-plane-machine
  labels:
    cluster.x-k8s.io/contract: v1beta2
spec:
  template:
    spec:
      # Placeholders replaced by the ClusterClass patches.
      region: set-by-clusterclass
      planID: set-by-clusterclass
      osID: 2284
      sshKey: []
