package services

import (
	"strings"

	"github.com/pkg/errors"
	"sigs.k8s.io/yaml"
)

const cloudConfigHeader = "#cloud-config"

// PrependCloudConfigRunCmds inserts commands at the front of the runcmd list of a
// cloud-config document, creating the list if it does not exist, so they run before
// the kubeadm commands generated by Cluster API (for example to open the firewall
// before the load balancer health checks a control plane). Documents that are not
// cloud-config (for example ignition or a shell script) are returned unchanged.
// A leading cloud-init "## template: jinja" line is preserved.
//
// The document is re-serialized, so comments and key order are not preserved;
// cloud-init does not depend on either.
func PrependCloudConfigRunCmds(userData string, cmds []string) (string, error) {
	if len(cmds) == 0 {
		return userData, nil
	}

	prefix, body := splitCloudConfigHeader(userData)
	if body == "" {
		return userData, nil
	}

	var doc map[string]interface{}
	if err := yaml.Unmarshal([]byte(body), &doc); err != nil {
		return "", errors.Wrap(err, "failed to parse cloud-config user data")
	}
	if doc == nil {
		doc = map[string]interface{}{}
	}

	var runcmd []interface{}
	if existing, ok := doc["runcmd"]; ok && existing != nil {
		list, ok := existing.([]interface{})
		if !ok {
			return "", errors.New("cloud-config runcmd is not a list")
		}
		runcmd = list
	}
	prepended := make([]interface{}, 0, len(cmds)+len(runcmd))
	for _, cmd := range cmds {
		prepended = append(prepended, cmd)
	}
	doc["runcmd"] = append(prepended, runcmd...)

	out, err := yaml.Marshal(doc)
	if err != nil {
		return "", errors.Wrap(err, "failed to serialize cloud-config user data")
	}

	return prefix + cloudConfigHeader + "\n" + string(out), nil
}

// splitCloudConfigHeader returns the lines preceding the "#cloud-config" header
// (cloud-init allows a "## template: jinja" line in front of it) and the
// document body. The body is empty when the data is not a cloud-config document.
func splitCloudConfigHeader(userData string) (prefix, body string) {
	rest := userData
	for {
		line, tail, _ := strings.Cut(rest, "\n")
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, cloudConfigHeader):
			return prefix, tail
		case trimmed == "" || strings.HasPrefix(trimmed, "## template:"):
			prefix += line + "\n"
			rest = tail
			if rest == "" {
				return "", ""
			}
		default:
			return "", ""
		}
	}
}
