apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# All bare metal: builds on the bare-metal flavor and moves the control plane
# to bare metal as well.
resources:
- ../bare-metal
- vultr-bare-metal-control-plane-machine.yaml
- vultr-bare-metal-control-plane.yaml
patches:
- path: clusterclass-patch.yaml
  target:
    group: cluster.x-k8s.io
    version: v1beta2
    kind: ClusterClass
    name: vultr-bare-metal
- path: cluster-template-patch.yaml
  target:
    group: cluster.x-k8s.io
    version: v1beta2
    kind: Cluster
